### ISSUE TITLE
Support for App Engine Python 3 Standard Environment

### ISSUE THREAD

**Issue by shlomgad** [salrashid123/flask-gcp-log-groups#4]
Could not get it to work on the python 3 app engine environment (logs still not correlated to the requests).
Should it work on that environment ?

**Comment by Gaket** [comment]
I would be happy to see the answer as well.

**Comment by salrashid123** [comment]
sorry for the late reply (didn't realize this comment was made).

i'm not sure if it'll help at this point but this should work on GAE python3 as well.

appengine (original) automatically did correlaton by simply collapsing the stdout of each instance.   Unfortunately appgengine (the new versions (python3, go11, java8) will not do that for you so anything writtend to stdout/sterr or using ordinary package loggers will not correlate.   Instead, you need to emit logs via the logging API in a very specific manner to get correlation working.  here a [medium article](https://medium.com/google-cloud/combining-correlated-log-lines-in-google-stackdriver-dd23284aeb29) about all this from a bit ago

**Comment by salrashid123** [comment]
just verified it works on python3,...i just need to push a new pip3 package up
(i'll take care of that today after a PR thats inflight at the moment)
