### ISSUE TITLE
Root log message severity set to wrong level with mixed severity sub-messages

### ISSUE THREAD

**Issue by mrnitrate** [salrashid123/flask-gcp-log-groups#6]
Currently, the root log message severity is set to the `min()` of its sub-messages severity (if any). For example, this causes log threads with 'debug' and 'info' level logs to set the root log message severity to 'debug' instead of 'info'.

There is even a comment on line 106 to "apply the max level to the root log message" but min was used instead.

PR to fix this https://github.com/salrashid123/flask-gcp-log-groups/pull/5

**Comment by salrashid123** [comment]
Thansk for the PR. 
merged

**Comment by salrashid123** [comment]
hi- i think it was just a typo comment..and whats needed is 

```
severity= min(self.mLogLevels)
```
---
if i use `min`, the top level log carries the child log level:

- error logs

```python
  app.logger.setLevel(logging.DEBUG)
  app.logger.error("an error log")
  app.logger.info("an info log")
```
![error_min](https://user-images.githubusercontent.com/11149054/102350778-71533700-3f73-11eb-9dab-87a4a064584e.png)


and debug

```python
def default():
  app.logger.setLevel(logging.DEBUG)
  app.logger.debug("a debug log")
  app.logger.info("an info log")
```

![debug_min](https://user-images.githubusercontent.com/11149054/102350810-7d3ef900-3f73-11eb-89b6-2e25e53a45c6.png)

---

if i used `max` per this PR, it woudn't reflect the child log level

- error
 
![error_max](https://user-images.githubusercontent.com/11149054/102350847-8a5be800-3f73-11eb-9107-1333ed760ed7.png)

- debug 
![debug_max](https://user-images.githubusercontent.com/11149054/102350872-93e55000-3f73-11eb-8579-cfa3910a9a38.png)



---

i think the top-level logs shoudl show the highest severity?  Maybe theres an issue in the UI where the min+debug logs shows the whole parent as debug (it should be info similar to how error appears)...

**Comment by mrnitrate** [comment]
@salrashid123 Interesting, Thanks for looking into this.  I agree I think "the top-level logs should show the highest severity'.  It's just odd to me that the 'error' level is lower than the 'info' level. (`min()`)  According to their documentation, it should be a higher (https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity). 

I think I found the root cause of this behavior here.  On this line, https://github.com/salrashid123/flask-gcp-log-groups/blob/87054e6b203b53c4d402a470ded00103b5291944/flask_gcp_log_groups/gcp_logging.py#L50 we append the STRING value of the log records `levelname` and not its INT value via `levelno` like we are checking online 48. 

This causes the `min()` or `max()` calls to evaluate the STRINGS of the levels and not their integer values and return the incorrect root message SEVERITY.

We should store the `record.levelno` in `mLogLevels` and not `record.levelname` for evaluating the highest severity level but then use that levels `levelname` when setting the parents severity (https://github.com/salrashid123/flask-gcp-log-groups/blob/87054e6b203b53c4d402a470ded00103b5291944/flask_gcp_log_groups/gcp_logging.py#L117).

I will submit another PR to fix this logic, I think we should turn `mLogLevels` into a dict with `levelno` as the key and `levelname` as the value and output the value of the max found `mLogLevels`.

**Comment by salrashid123** [comment]
thanks...i was actually on another screen about this.  PTAL on the commit i just made
